name: svelte_js
description: An absolute bare-bones web app.
version: 1.0.0-dev
publish_to: none

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  http: ^1.3.0
  markdown: ^7.3.0
  meta: ^1.16.0
  web: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.15
  build_web_compilers: ^4.1.1
  lints: ^5.1.1
