name: svelte_js
description: An absolute bare-bones web app.
version: 1.0.0-dev
publish_to: none

environment:
  sdk: ^3.5.0-0

# Add regular dependencies here.
dependencies:
  meta: ^1.15.0
  web: ^0.5.1

dev_dependencies:
  build_runner: ^2.4.11
  build_web_compilers: ^4.0.10
  lints: ^4.0.0
